name: Deploy for illuminaty
on:
  push:
    branches:
      - main
env:
  AWS_REGION: ap-northeast-1
  AWS_ROLE_ARN: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_ROLE_NAME }} # GitHub　Actions用に作成したIAMロールのARN

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Configure AWS credentials from IAM Role
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Checkout
        uses: actions/checkout@main # リポジトリをチェックアウト

      - name: Upload files # S3にデプロイ
        run: aws s3 cp --region ap-northeast-1 index.html s3://${{secrets.AWS_BUCKET_NAME}}/index.html

      - name: Clear cache
        run: |
          aws cloudfront create-invalidation --distribution-id ${{secrets.AWS_CLOUDFRONT_NAME}} --paths "/*"
